/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#dee3eb",
        "on-primary": "#ffffff",
        "charcoal-ink": "#20252B",
        "secondary": "#4d5f7b",
        "on-primary-fixed-variant": "#5d4200",
        "tertiary": "#615e56",
        "diwali-gold": "#F4B51B",
        "on-tertiary-fixed-variant": "#49473f",
        "on-tertiary-container": "#504e46",
        "cream-canvas": "#FFF9EE",
        "on-secondary-fixed-variant": "#354862",
        "primary-container": "#f4b51b",
        "surface-container-highest": "#dee3eb",
        "on-surface": "#171c22",
        "inverse-surface": "#2c3137",
        "alert-red": "#C94232",
        "surface-container": "#eaeef6",
        "on-primary-container": "#664900",
        "on-secondary": "#ffffff",
        "pure-surface": "#FFFFFF",
        "surface-dim": "#d6dae2",
        "secondary-fixed": "#d4e3ff",
        "surface-container-high": "#e4e8f1",
        "primary-fixed-dim": "#fcbc24",
        "success-green": "#23834A",
        "primary": "#7b5800",
        "on-secondary-container": "#4f627e",
        "error-container": "#ffdad6",
        "primary-fixed": "#ffdea4",
        "inverse-primary": "#fcbc24",
        "tertiary-fixed": "#e7e2d7",
        "on-primary-fixed": "#261900",
        "on-surface-variant": "#504533",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "night-navy": "#10243D",
        "outline-variant": "#d4c4ac",
        "muted-slate": "#68717C",
        "on-error-container": "#93000a",
        "secondary-container": "#cbdeff",
        "tertiary-container": "#c4bfb5",
        "tertiary-fixed-dim": "#cbc6bc",
        "secondary-fixed-dim": "#b5c8e8",
        "on-tertiary-fixed": "#1d1c15",
        "background": "#f7f9ff",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f0f4fc",
        "inverse-on-surface": "#edf1f9",
        "surface": "#f7f9ff",
        "on-secondary-fixed": "#071c35",
        "error": "#ba1a1a",
        "soft-border": "#E8E1D5",
        "surface-tint": "#7b5800",
        "surface-bright": "#f7f9ff",
        "outline": "#827561",
        "on-background": "#171c22"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.25rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-mobile": "1rem",
        "space-xs": "0.5rem",
        "space-md": "1.5rem",
        "gutter": "1.5rem",
        "space-lg": "2rem",
        "space-sm": "1rem",
        "margin-mobile": "1rem",
        "margin": "2rem",
        "space-xl": "3rem"
      },
      fontFamily: {
        "display": ["Outfit", "sans-serif"],
        "body": ["Outfit", "sans-serif"],
        "body-lg": ["Outfit", "sans-serif"],
        "body-md": ["Outfit", "sans-serif"],
        "body-sm": ["Outfit", "sans-serif"],
        "label-lg": ["Outfit", "sans-serif"],
        "label-md": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "headline-sm": ["Outfit", "sans-serif"],
        "mono": ["Geist Mono", "monospace"],
        "mono-price-lg": ["Geist Mono", "monospace"],
        "mono-price-md": ["Geist Mono", "monospace"],
        "mono-data": ["Geist Mono", "monospace"]
      }
    }
  },
  plugins: [],
}
